### ISSUE TITLE
The new logo

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#121]
![markuplint logo](https://cdn.rawgit.com/YusukeHirao/markuplint/HEAD/media/logo-v.svg)

The current logo was made just quick by me.
I want a designer to improve it properly.

Want:
- Accessible.
- Compatible with dark mode.
- Usable for a small area.
- Monochromatic variation.

**Comment by kagankan** [comment]
@YusukeHirao 

I made a proposal of new logo! (based on your great original one!)
but I'm not a designer, am just a engineer.  sorry!

![image (16)](https://user-images.githubusercontent.com/34136752/163711918-dbd785d2-b133-4d66-aacf-b83ce35d04b7.png)

- Use new main color `#1374e1` . This color is more vivid than current one, and has a contrast ratio of more than 4.5:1 with `#000` and `#fff`.
- And also use darker color `#143c66` instead of black. 
- Separate the blue part of "M"  (that means "check mark ✔", right?) from other parts in order to make it easy to identify even if it is monochromatic.
- Use "Source Sans Pro" font
- Use single color for "markuplint" because it is an unique name by entire string of "markuplint" (not only "markup" or only "lint"), I think
- Omit `<` and `>`  from logo to simplify logo.

Please tell me your thoughts and other markuplint users' thoughts!

**Comment by YusukeHirao** [comment]
@kagankan 

Thank you for your awesome ideas!

## Good Ideas
- New Colors (Thanks, kept contrast)
- Rounded corners
- Added gap to areas

## Questions
- Why _Oblique_ type? (markuplint provides **stability**.)
- Why "Source Sans Pro" Font? (I want to know the reason.)

## Needs
- Colored dark version

**Comment by kagankan** [comment]
@YusukeHirao 

Thank you for your comment!


>Why Oblique type? 

I felt somewhat cool or stylish by Oblique type.

However,

> (markuplint provides stability.)

That's true, 
exactly as you said.
The logo should represent stability of markuplint.

I'll try to make Not Oblique type version!

>Why "Source Sans Pro" Font? 

The shape of the bottom of "l" is rounded. This matches corner-rounded style... I think.
(This is mostly my taste)

I need any ideas for better font for logotype!

>Colored dark version

OK. I'll also make it.

It will be weekend when I update this because I don't have much time on weekdays...

**Comment by kagankan** [comment]
@YusukeHirao 
![image (17)](https://user-images.githubusercontent.com/34136752/164968340-eb7d0b00-914b-4cfc-bd21-f3eea67d48ea.png)

I updated the new logo design.

- Changed it to not oblique style.
- Changed `#143c66` to `#16324d`. It is more darker/subdued color and makes me feel stability/reliability.
- Made colored dark version
  - I tried to make white and blue colored version, but it didn't match with me. I think white outlined style is better way to use colored logo in dark background.

I tried some variations of dark version: 
![image (18)](https://user-images.githubusercontent.com/34136752/164968423-79427742-b2ce-4043-9354-4dd5ad3778c8.png)

How do you think?

**Comment by YusukeHirao** [comment]
Below is the final results of the voting that was planned by my decision.

https://twitter.com/markuplint/status/1573166380937252865

I will adopt the idea that is designed by @kagankan. Thank you so much!

But @MirukaJP, I need your help.
Your ideas are awesome, and the graphical balance is great in particular.
Could you coordinate (colors, widths, rounds, balance, and more) it finally from kagankan's idea? And I want to adopt the logotype to be your idea PT Sans Caption.

**Comment by YusukeHirao** [comment]
The logo is decided.

Thanks for your idea, @kagankan.
Thanks for refining it discretely, @MirukaJP.

I will add the regulation of this logo to the next version website.

![markuplint logo](https://user-images.githubusercontent.com/953956/204073484-0c5ae8df-c96c-416c-8bf9-dbac15cc0773.png)
