### ISSUE TITLE
Ignore blocks

### ISSUE THREAD

**Issue by niksy** [markuplint/markuplint#19]
Is there possibility of adding option to ignore certain parts of the markup? For example, common use case when using PHP templates is to use `<?php … ?>` blocks which can create confusion for markuplint parser. Is it possible to create some option (or rule) to ignore those blocks (via regex, …)?

**Comment by YusukeHirao** [comment]
Hi @niksy. Thanks for question.

It is under design. I am suffering from it. I am thinking that it may be unnecessary because "Ignore Option" is necessary or if there is a PHP Parser, it can be supplemented.

Certainly, excluding blocks via regular expressions is generic. But I am not a Parser expert, so I fear the occurrence of bugs and performance degradation due to regular expressions. Also, I am not confident of doing the correct design.

I want to hear your opinion.

**Comment by niksy** [comment]
What about proposed `php/markuplint-rule-ignore-php-code` rule? Is this something that has initial implementation or is it only planned?

Applying PHP parser is one way to do that, and probably more error-prone since Markuplint can cover more edge cases that custom regular expression, but regular expression gives you more flexibility. I don’t think performance degradation is of major concern, but it can be mentioned as caveat in README, and for everything else we could suggest creating custom rule which could apply more flexible and performant implementation.
