### ISSUE TITLE
Supporting for new angular syntax @if / @for / ...

### ISSUE THREAD

**Issue by AlexKarpov98** [markuplint/markuplint#1914]
Angular has introduced new html syntax like `@if`, `@for` etc.
(example: https://blog.angular-university.io/angular-if/)

Are there any plans to support this new syntax?
Additionally, how can I set up the `indentation` rule in the latest version of `markuplint`? Why was it removed?

The following configuration worked well with the older version of markuplint `(v2.9.0)`:
```
    "indentation": {
      "value": 2,
      "severity": "error"
    },
```

However once I started using the new angular html syntax like `@if`, `@for` - it started giving me linting errors.
That's the reason for opening this feature request.

**Comment by YusukeHirao** [comment]
@AlexKarpov98 

Currently, Angular is not supported, and since I am not using Angular myself, learning the syntax to implement it would take some time. There are many other priorities, so realistically, I hope that volunteers within the community could contribute to this. Regarding the `indentation` rule, it was dropped in version 3, so it's no longer available. I recommend using tools like **Prettier** or **Biom** for similar functionality. Thank you for using the tool and for your understanding.
