### ISSUE TITLE
PostHTML?

### ISSUE THREAD

**Issue by niksy** [markuplint/markuplint#20]
Have you considered using [PostHTML](https://github.com/posthtml/posthtml) as HTML parser? It is well-tested and has existed for sometime, and maybe Markuplint can use it’s parser and just focus on creating linting capabilities?

Or is Markuplint’s parser more powerful and flexible that PostHTML’s one?

**Comment by YusukeHirao** [comment]
Hi @niksy. 

Yes, I considered using PostHTML. But markuplint doesn't use PostHTML Parser. Because the AST of PostHTML Parser is not have location (line and cols). So markuplint used [Parse5](https://github.com/inikulin/parse5).

Parse 5 is a reliable library because it is also used in [JSDOM](https://github.com/jsdom/jsdom).

**Comment by niksy** [comment]
Cool!

**Comment by niksy** [comment]
@YusukeHirao just wanted to mention there is new HTML parser on the block: https://github.com/phtmlorg/phtml
