### ISSUE TITLE
Supporting for `<search>`

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#762]
## Document or Issue Link

https://github.com/whatwg/html/pull/7320

**Comment by SaekiTominaga** [comment]
Currently, replacing `<div role="search">` with `<search>` has a disadvantage since the browser implementation is not advanced.

Scott O'Bother said this in [a blog post](https://www.scottohara.me/blog/2023/03/24/search-element.html).

> Please be aware that this element landing in the HTML spec today **does not mean it is available in browsers today**. Issues have been filed to implement the search element the major browsers, including the necessary accessibility mappings. Keep this in mind before you get all super excited and willy nilly add this new element to your pages.

So as a interim measure, could you consider using `markuplint:recommended` to prompt the `search` element to set `role="search"`? (e.g. `nodeRules` rule)

- 👎 `<search>`
- 👍 `<search role="search">`

**Comment by YusukeHirao** [comment]
@SaekiTominaga

Sure, I'll do it. Thank you for your advice.
